version: 0.2

phases:
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
    - URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_NAME}
    # - REPO=$(aws ecr describe-repositories --repository-names go/server --output text --query "repositories[0].repositoryUri")
    # - IMAGE=$REPO:latest
  build:
    commands:
    - docker build -t $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
    - docker push $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
    - printf '{"Version":"1.0","ImageURI":"%s"}' $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imageDetail.json
artifacts:
  files: imageDetail.json