version: 0.2

phases:
  pre_build:
    commands:
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 567204659259.dkr.ecr.ap-northeast-1.amazonaws.com
    - REPO=$(aws ecr describe-repositories --repository-names go/server --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO:latest
  build:
    commands:
    - docker build -t $IMAGE .
    - docker push $IMAGE
  post_build:
    commands:
    - printf '[{"name":"go-server","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json