# version: '3'
# services:
#   go:
#     build:
#       context: .
#       dockerfile: DockerFile
#     command: /bin/sh -c "go run main.go"
#     stdin_open: true
#     tty: true
#     volumes:
#       - .:/app

version: "3"

services:
  db:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"

  web:
    build: ./docker/golang
    tty: true
    environment:
      APP_MODE: local
      DB_USER: localuser
      DB_PASSWORD: localpass
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: go_sample
      DB_NAME_TEST: go_sample_test
      DB_LOC: Asia%2FTokyo
    volumes:
      - "./src:/tmp/mnt/src"
    depends_on:
      - db

  proxy:
    build: ./docker/nginx
    ports:
      - 8082:80
    depends_on:
      - web
