version: "3"

services:
  db:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
      TZ: Asia/Tokyo
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3310:3306"

  web:
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    ports:
      - 3000:9000
    tty: true
    environment:
      APP_MODE: local
      DB_USER: localuser
      DB_PASSWORD: localpass
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: go_sample
      DB_NAME_TEST: go_sample_test
      DB_LOC: Asia%2FTokyo
    volumes:
      - "./src:/tmp/mnt/src"
    depends_on:
      - db

  proxy:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - web
